apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
    containers:
    - name: swiggy
      image: msithaba/swiggy-clone:latest
      ports:
      - containerPort: 3000   # Use port 3000