apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  selector:
    app: swiggy
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80 
    targetPort: 3000
  type: LoadBalancer